### ISSUE TITLE
Support for Embedding Live Polls Using iframes in Quarto Documents

### ISSUE THREAD

**Issue by RRMaximiliano** [coatless-quarto/embedio#10]
**Is your feature request related to a problem? Please describe.**
I'm trying to embed live polls in a Quarto document using an iframe. This method worked well in RMarkdown, but it doesn't function properly in Quarto. Specifically, when I include the iframe code inside a `div` element with an HTML code block, the poll fails to embed or display correctly. This is frustrating as I rely on live polls for interactive content in my presentations and documents.

**Describe the solution you'd like**
I would like Quarto (or embedio?) to support embedding live polls using iframes, similar to how it worked in RMarkdown. Ideally, the iframe should render and display the poll correctly when included in a Quarto document. Additionally, it would be helpful if the Embedio extension could handle live presentations and polls, providing a seamless way to integrate such content.

**Describe alternatives you've considered**
I've considered different HTML configurations within Quarto, but none have worked so far. 

**Additional context**
Here’s an example of the iframe code that worked in RMarkdown:

```html
<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/rjGrLtq2xnzTicvBvI8Fm?controls=none&short_poll=true" width="100%" height="100%" frameBorder="0" allowFullScreen style="max-width: 1600px; max-height: 1600px; margin: 0 auto; display: block;"></iframe>
```
![image](https://github.com/user-attachments/assets/07760e85-69a4-4f4e-be53-c5408f244044)

In Quarto, the same code embedded as follows does not work:

```
  <div>
  ```{=html}
  <iframe src="https://embed.polleverywhere.com/multiple_choice_polls/rjGrLtq2xnzTicvBvI8Fm?controls=none&short_poll=true" width="100%" height="100%" frameBorder="0" allowFullScreen style="max-width: 1600px; max-height: 1600px; margin: 0 auto; display: block;"></iframe>
  ```
  </div>
```

I would appreciate guidance on how to achieve this.

**Comment by coatless** [comment]
I think you're using the following:

````md
```{=html}
<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/rjGrLtq2xnzTicvBvI8Fm?controls=none&short_poll=true" frameBorder="0" allowFullScreen style="max-width: 1600px; max-height: 1600px; margin: 0 auto; display: block; width:100%; height:100%">
</iframe>
```
````

By changing some CSS, the `min-width` and `max-width` being set to 100%, I think the problem resolves itself.

So, what happens if you try:

````md
```{=html}
<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/rjGrLtq2xnzTicvBvI8Fm?controls=none&short_poll=true" style="max-width: 1600px; max-height: 1600px; margin: 0 auto; display: block; min-width:100%; min-height:100%">
</iframe>
```
````

On my end this gives:

<img width="1029" alt="Demo of the polleverywhere loading" src="https://github.com/user-attachments/assets/abde9cf5-3922-41eb-8653-c5ceccfdbeb7">

<details>
<summary>Source of Quarto document MWE</summary>

````md
---
title: "Example HTML Webpage"
format: html
embed-resources: true
---

## Welcome

```{=html}
<iframe src="https://embed.polleverywhere.com/multiple_choice_polls/rjGrLtq2xnzTicvBvI8Fm?controls=none&short_poll=true" style="max-width: 1600px; max-height: 1600px; margin: 0 auto; display: block; min-width:100%; min-height:100%">
</iframe>
```
````
</details>


I'm not 100% sure this is the right place to raise this as an issue. This is probably better over at the main [quarto project](https://github.com/quarto-dev/quarto-cli) as this seems to be an issue with default bootstrap styling on an iframe or the underlying polleverywhere website not allowing certain resources to load.

**Comment by RRMaximiliano** [comment]
Hi @coatless I will close the issue and move it to quarto. I, unfortunately, didn't get the same results as you got even after using your MWE.  Thanks. Great extension btw.
